<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="11.003" tests="7" failures="1">
  <testsuite name="Root Suite" timestamp="2022-10-14T11:24:11" tests="0" file="cypress/e2e/spec.cy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="empty spec" timestamp="2022-10-14T11:24:11" tests="7" time="10.992" failures="1">
    <testcase name="empty spec loads the homepage" time="0.568" classname="loads the homepage">
    </testcase>
    <testcase name="empty spec performs a sum that always passes" time="1.058" classname="performs a sum that always passes">
    </testcase>
    <testcase name="empty spec performs a sum that will result in flake ~50% of the time" time="0.983" classname="performs a sum that will result in flake ~50% of the time">
    </testcase>
    <testcase name="empty spec performs a sum that always fails" time="0.000" classname="performs a sum that always fails">
      <failure message="Timed out retrying after 4000ms: expected &apos;&lt;div.CalculationResult&gt;&apos; to have text &apos;0&apos;, but the text was &apos;-5&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<div.CalculationResult>' to have text '0', but the text was '-5'
    at Context.eval (webpack:///./cypress/e2e/spec.cy.js:41:42)

      + expected - actual

      -'-5'
      +'0'
      ]]></failure>
    </testcase>
    <testcase name="empty spec is a test that passes" time="1.037" classname="is a test that passes">
    </testcase>
    <testcase name="empty spec is a test that passes v2" time="1.031" classname="is a test that passes v2">
    </testcase>
    <testcase name="empty spec is a test that fails around 25% of the time" time="1.125" classname="is a test that fails around 25% of the time">
    </testcase>
  </testsuite>
</testsuites>